package il.ac.hit.pooly;

public class Demo {
    public static void main(String[] args) {
        ThreadsPool threadsPool = new ThreadsPool(10);
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("killing myself", 2));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("eating", 50));
        threadsPool.submit(new DemoTask("sleeping", 1));
        threadsPool.start();
    }
}
